USE fitneedsdb;

SET FOREIGN_KEY_CHECKS = 0;

-- =========================================================
-- 배정된 수업(SCHEDULE) 더미 데이터 생성
-- =========================================================

-- =========================================================
-- 0) 기본 데이터 먼저 생성 (없으면)
-- =========================================================

-- ADMIN 계정
SET @ADMIN_EMAIL := 'admin@naver.com';
SET @ADMIN_ID_NEW := '11111111-1111-1111-1111-111111111111';
SET @PW_ADMIN  := '$2b$10$3zFdrHolW/N.cCLAf1ix.eLsbXbRqeDpsmeeh7C0mFzKsrTNXqsMO';
SET @PW_TEACHER := '$2b$10$8U.ayeu6Fqex1abqiHE8uuXXzpwnDGNTNYMiFaM7TB9npimB5gz8m';

INSERT INTO USERS_ADMIN (USER_ID, USER_NAME, EMAIL, PASSWORD, PHONE_NUMBER, ROLE, BRCH_ID, IS_ACTIVE, AGREE_AT)
SELECT @ADMIN_ID_NEW, 'ADMIN', @ADMIN_EMAIL, @PW_ADMIN, '010-0000-0000', 'ADMIN', NULL, 1, NOW()
WHERE NOT EXISTS (SELECT 1 FROM USERS_ADMIN WHERE EMAIL = @ADMIN_EMAIL);

SET @ADMIN_ID := (SELECT USER_ID FROM USERS_ADMIN WHERE EMAIL = @ADMIN_EMAIL LIMIT 1);

-- BRANCH 생성
INSERT INTO BRANCH (BRCH_NM, ADDR, OPER_YN, REG_DT, UPD_DT, PHONE)
SELECT 'DUMMY_강남점', '서울 강남구', 1, NOW(), NOW(), '02-0000-0001'
WHERE NOT EXISTS (SELECT 1 FROM BRANCH WHERE BRCH_NM = 'DUMMY_강남점');

INSERT INTO BRANCH (BRCH_NM, ADDR, OPER_YN, REG_DT, UPD_DT, PHONE)
SELECT 'DUMMY_홍대점', '서울 마포구', 1, NOW(), NOW(), '02-0000-0002'
WHERE NOT EXISTS (SELECT 1 FROM BRANCH WHERE BRCH_NM = 'DUMMY_홍대점');

-- SPORT_TYPE 생성
INSERT INTO SPORT_TYPE (SPORT_NM, SPORT_MEMO, USE_YN, REG_DT, UPD_DT, DEL_DT)
SELECT 'DUMMY_PT', '더미 종목', 1, NOW(), NOW(), NULL
WHERE NOT EXISTS (SELECT 1 FROM SPORT_TYPE WHERE SPORT_NM = 'DUMMY_PT');

INSERT INTO SPORT_TYPE (SPORT_NM, SPORT_MEMO, USE_YN, REG_DT, UPD_DT, DEL_DT)
SELECT 'DUMMY_필라테스', '더미 종목', 1, NOW(), NOW(), NULL
WHERE NOT EXISTS (SELECT 1 FROM SPORT_TYPE WHERE SPORT_NM = 'DUMMY_필라테스');

INSERT INTO SPORT_TYPE (SPORT_NM, SPORT_MEMO, USE_YN, REG_DT, UPD_DT, DEL_DT)
SELECT 'DUMMY_요가', '더미 종목', 1, NOW(), NOW(), NULL
WHERE NOT EXISTS (SELECT 1 FROM SPORT_TYPE WHERE SPORT_NM = 'DUMMY_요가');

-- 변수 설정
SET @T1 := '3A1C1111-2222-3333-4444-555555555555';
SET @T2 := '7B2D1111-2222-3333-4444-555555555555';

SET @BR1 := (SELECT BRCH_ID FROM BRANCH WHERE BRCH_NM='DUMMY_강남점' ORDER BY BRCH_ID DESC LIMIT 1);
SET @BR2 := (SELECT BRCH_ID FROM BRANCH WHERE BRCH_NM='DUMMY_홍대점' ORDER BY BRCH_ID DESC LIMIT 1);

SET @SP1 := (SELECT SPORT_ID FROM SPORT_TYPE WHERE SPORT_NM='DUMMY_PT' ORDER BY SPORT_ID DESC LIMIT 1);
SET @SP2 := (SELECT SPORT_ID FROM SPORT_TYPE WHERE SPORT_NM='DUMMY_필라테스' ORDER BY SPORT_ID DESC LIMIT 1);
SET @SP3 := (SELECT SPORT_ID FROM SPORT_TYPE WHERE SPORT_NM='DUMMY_요가' ORDER BY SPORT_ID DESC LIMIT 1);

-- 강사 계정 생성
INSERT INTO USERS_ADMIN (USER_ID, USER_NAME, EMAIL, PASSWORD, PHONE_NUMBER, ROLE, BRCH_ID, IS_ACTIVE, AGREE_AT)
VALUES
    (@T1, '더미강사1', 'dummy_teacher1@test.com', @PW_TEACHER, '010-8000-1001', 'TEACHER', @BR1, 1, NOW()),
    (@T2, '더미강사2', 'dummy_teacher2@test.com', @PW_TEACHER, '010-8000-1002', 'TEACHER', @BR2, 1, NOW())
ON DUPLICATE KEY UPDATE
    USER_NAME     = VALUES(USER_NAME),
    BRCH_ID       = VALUES(BRCH_ID);

-- 강사 프로필 생성
INSERT INTO TEACHER_PROFILE (USER_ID, BRCH_ID, STTS_CD, HIRE_DT, INTRO, REG_DT, UPD_DT, UPD_USER_ID)
VALUES
    (@T1, @BR1, 'ACTIVE', '2025-01-01', '더미강사1 소개', NOW(), NOW(), @ADMIN_ID),
    (@T2, @BR2, 'ACTIVE', '2025-01-01', '더미강사2 소개', NOW(), NOW(), @ADMIN_ID)
ON DUPLICATE KEY UPDATE
    BRCH_ID = VALUES(BRCH_ID),
    UPD_DT  = NOW();

-- =========================================================
-- 1) PROGRAM 생성 (프로그램이 있어야 스케줄 생성 가능)
-- =========================================================
INSERT INTO PROGRAM (PROG_NM, SPORT_ID, BRCH_ID, USE_YN, ONE_TIME_AMT, REG_DT, UPD_DT)
SELECT 'DUMMY_강남PT', @SP1, @BR1, 1, 50000.0000, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM PROGRAM WHERE PROG_NM = 'DUMMY_강남PT');

INSERT INTO PROGRAM (PROG_NM, SPORT_ID, BRCH_ID, USE_YN, ONE_TIME_AMT, REG_DT, UPD_DT)
SELECT 'DUMMY_강남필라테스', @SP2, @BR1, 1, 40000.0000, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM PROGRAM WHERE PROG_NM = 'DUMMY_강남필라테스');

INSERT INTO PROGRAM (PROG_NM, SPORT_ID, BRCH_ID, USE_YN, ONE_TIME_AMT, REG_DT, UPD_DT)
SELECT 'DUMMY_홍대요가', @SP3, @BR2, 1, 35000.0000, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM PROGRAM WHERE PROG_NM = 'DUMMY_홍대요가');

SET @PROG1 := (SELECT PROG_ID FROM PROGRAM WHERE PROG_NM='DUMMY_강남PT' ORDER BY PROG_ID DESC LIMIT 1);
SET @PROG2 := (SELECT PROG_ID FROM PROGRAM WHERE PROG_NM='DUMMY_강남필라테스' ORDER BY PROG_ID DESC LIMIT 1);
SET @PROG3 := (SELECT PROG_ID FROM PROGRAM WHERE PROG_NM='DUMMY_홍대요가' ORDER BY PROG_ID DESC LIMIT 1);

-- =========================================================
-- 2) SCHEDULE 생성 (강사별 배정된 수업)
-- =========================================================

-- 더미강사1 (@T1) - 강남점 PT 및 필라테스
INSERT INTO SCHEDULE (PROG_ID, USER_ID, BRCH_ID, STRT_DT, STRT_TM, END_TM, MAX_NOP_CNT, RSV_CNT, STTS_CD, DESCRIPTION, REG_DT, UPD_DT)
VALUES
    -- 오늘 기준 과거 수업
    (@PROG1, @T1, @BR1, DATE_SUB(CURDATE(), INTERVAL 2 DAY), '09:00:00', '10:00:00', 5, 4, 'COMPLETED', 'PT 개인 레슨', NOW(), NOW()),
    (@PROG1, @T1, @BR1, DATE_SUB(CURDATE(), INTERVAL 1 DAY), '10:00:00', '11:00:00', 5, 5, 'COMPLETED', 'PT 개인 레슨', NOW(), NOW()),

    -- 오늘 수업
    (@PROG1, @T1, @BR1, CURDATE(), '14:00:00', '15:00:00', 5, 3, 'CONFIRMED', 'PT 오후 수업', NOW(), NOW()),
    (@PROG2, @T1, @BR1, CURDATE(), '16:00:00', '17:00:00', 10, 7, 'CONFIRMED', '필라테스 그룹 수업', NOW(), NOW()),

    -- 미래 수업
    (@PROG1, @T1, @BR1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '09:00:00', '10:00:00', 5, 2, 'CONFIRMED', 'PT 개인 레슨', NOW(), NOW()),
    (@PROG2, @T1, @BR1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '11:00:00', '12:00:00', 10, 5, 'CONFIRMED', '필라테스 그룹 수업', NOW(), NOW()),
    (@PROG1, @T1, @BR1, DATE_ADD(CURDATE(), INTERVAL 2 DAY), '14:00:00', '15:00:00', 5, 1, 'CONFIRMED', 'PT 개인 레슨', NOW(), NOW()),
    (@PROG2, @T1, @BR1, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '10:00:00', '11:00:00', 10, 0, 'OPEN', '필라테스 그룹 수업', NOW(), NOW()),
    (@PROG1, @T1, @BR1, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '15:00:00', '16:00:00', 5, 0, 'OPEN', 'PT 개인 레슨', NOW(), NOW()),
    (@PROG2, @T1, @BR1, DATE_ADD(CURDATE(), INTERVAL 5 DAY), '11:00:00', '12:00:00', 10, 0, 'OPEN', '필라테스 그룹 수업', NOW(), NOW());

-- 더미강사2 (@T2) - 홍대점 요가
INSERT INTO SCHEDULE (PROG_ID, USER_ID, BRCH_ID, STRT_DT, STRT_TM, END_TM, MAX_NOP_CNT, RSV_CNT, STTS_CD, DESCRIPTION, REG_DT, UPD_DT)
VALUES
    -- 과거 수업
    (@PROG3, @T2, @BR2, DATE_SUB(CURDATE(), INTERVAL 3 DAY), '08:00:00', '09:00:00', 15, 12, 'COMPLETED', '아침 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_SUB(CURDATE(), INTERVAL 2 DAY), '18:00:00', '19:00:00', 15, 15, 'COMPLETED', '저녁 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_SUB(CURDATE(), INTERVAL 1 DAY), '10:00:00', '11:00:00', 15, 10, 'COMPLETED', '요가 수업', NOW(), NOW()),

    -- 오늘 수업
    (@PROG3, @T2, @BR2, CURDATE(), '08:00:00', '09:00:00', 15, 8, 'CONFIRMED', '아침 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, CURDATE(), '19:00:00', '20:00:00', 15, 11, 'CONFIRMED', '저녁 요가', NOW(), NOW()),

    -- 미래 수업
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '08:00:00', '09:00:00', 15, 6, 'CONFIRMED', '아침 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '18:00:00', '19:00:00', 15, 9, 'CONFIRMED', '저녁 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 2 DAY), '10:00:00', '11:00:00', 15, 3, 'CONFIRMED', '요가 수업', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '08:00:00', '09:00:00', 15, 0, 'OPEN', '아침 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '19:00:00', '20:00:00', 15, 0, 'OPEN', '저녁 요가', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 5 DAY), '10:00:00', '11:00:00', 15, 0, 'OPEN', '요가 수업', NOW(), NOW()),
    (@PROG3, @T2, @BR2, DATE_ADD(CURDATE(), INTERVAL 6 DAY), '18:00:00', '19:00:00', 15, 0, 'OPEN', '저녁 요가', NOW(), NOW());

SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================
-- 검증 쿼리
-- =========================================================
SELECT '=== 생성된 스케줄 목록 ===' AS INFO;

SELECT
    s.SCHD_ID,
    s.USER_ID,
    ua.USER_NAME AS 강사명,
    p.PROG_NM AS 프로그램명,
    b.BRCH_NM AS 지점명,
    s.STRT_DT AS 수업날짜,
    s.STRT_TM AS 시작시간,
    s.END_TM AS 종료시간,
    s.MAX_NOP_CNT AS 정원,
    s.RSV_CNT AS 예약인원,
    s.STTS_CD AS 상태
FROM SCHEDULE s
JOIN PROGRAM p ON p.PROG_ID = s.PROG_ID
JOIN BRANCH b ON b.BRCH_ID = s.BRCH_ID
JOIN USERS_ADMIN ua ON ua.USER_ID = s.USER_ID
WHERE s.USER_ID IN (@T1, @T2)
ORDER BY s.STRT_DT DESC, s.STRT_TM DESC;

SELECT '=== 강사별 수업 통계 ===' AS INFO;

SELECT
    ua.USER_NAME AS 강사명,
    COUNT(*) AS 총수업개수,
    SUM(CASE WHEN s.STTS_CD = 'COMPLETED' THEN 1 ELSE 0 END) AS 완료수업,
    SUM(CASE WHEN s.STTS_CD = 'CONFIRMED' THEN 1 ELSE 0 END) AS 확정수업,
    SUM(CASE WHEN s.STTS_CD = 'OPEN' THEN 1 ELSE 0 END) AS 모집중수업
FROM SCHEDULE s
JOIN USERS_ADMIN ua ON ua.USER_ID = s.USER_ID
WHERE s.USER_ID IN (@T1, @T2)
GROUP BY ua.USER_NAME;
